const flavorlists = [
  {
    name: "Original",
    bg: "24-optimized.webp",
    drink: "original-classic.webp",
    accent: "var(--color-monster-green)",
    glowColor: "#7CB701",
    notes: ["Citrus bite", "Classic rush", "Full throttle"],
    bestFor: "Late-night focus, heavy edits, and the original Monster hit.",
    rotation: "rotate-[-2deg]",
  },
  {
    
    name: "Zero Ultra",
    bg: "34343-optimized.webp",
    drink: "zero-ultra-silver.webp",
    elements: "ultra-white-elements-optimized.webp",
    accent: "var(--color-ultra-white)",
    glowColor: "#e8e8e8",
    notes: ["Zero sugar", "Clean finish", "Light citrus"],
    bestFor: "Gym sessions, crisp mornings, and a sharper zero-sugar feel.",
    rotation: "rotate-[1deg]",
  },
  {
    name: "Mango Loco",
    bg: "tecmango-optimized.webp",
    drink: "mango-loco.webp",
    elements: "mango-elements-optimized.webp",
    accent: "var(--color-juice-mango)",
    glowColor: "#e87820",
    notes: ["Mango punch", "Juiced body", "Tropical snap"],
    bestFor: "Hot afternoons, pre-game energy, and a louder flavor mood.",
    rotation: "rotate-[-1deg]",
  },
];

const cards = [
  {
    mp4: "/videos/f1.mp4",
    webm: "/videos/f1.webm",
    poster: "/videos/posters/f1-poster.webp",
    link: "https://youtube.com/shorts/VDodSsZwyRQ",
    rotation: "rotate-z-[-10deg]",
    name: "3ameed",
    img: "/images/profile-1.webp",
    translation: "translate-y-[-5%]",
  },
  {
    mp4: "/videos/f2.mp4",
    webm: "/videos/f2.webm",
    poster: "/videos/posters/f2-poster.webp",
    link: "https://youtube.com/shorts/njZie0bm2CY",
    rotation: "rotate-z-[4deg]",
    name: "EzLifts",
    img: "/images/profile-2.webp",
  },
  {
    mp4: "/videos/f3.mp4",
    webm: "/videos/f3.webm",
    poster: "/videos/posters/f3-poster.webp",
    link: "https://www.youtube.com/watch?v=30nxF0nsQzo",
    rotation: "rotate-z-[-4deg]",
    name: "GoldenGully",
    img: "/images/profile-3.webp",
    translation: "translate-y-[-5%]",
  },
  {
    mp4: "/videos/f4.mp4",
    webm: "/videos/f4.webm",
    poster: "/videos/posters/f4-poster.webp",
    link: "https://youtube.com/shorts/lAaRlpsElXs",
    rotation: "rotate-z-[4deg]",
    name: "MR.HUNGRY",
    img: "/images/profile-4.webp",
    translation: "translate-y-[5%]",
  },
  {
    mp4: "/videos/f5.mp4",
    webm: "/videos/f5.webm",
    poster: "/videos/posters/f5-poster.webp",
    link: "https://youtube.com/shorts/mObTVyFZkjI",
    rotation: "rotate-z-[-10deg]",
    name: "tyler tran",
    img: "/images/profile-5.webp",
  },
  {
    mp4: "/videos/f6.mp4",
    webm: "/videos/f6.webm",
    poster: "/videos/posters/f6-poster.webp",
    link: "https://youtube.com/shorts/2JsBa_yFkTE",
    rotation: "rotate-z-[4deg]",
    name: "Sunny",
    img: "/images/profile-6.webp",
    translation: "translate-y-[5%]",
  },
  {
    mp4: "/videos/f7.mp4",
    webm: "/videos/f7.webm",
    poster: "/videos/posters/f7-poster.webp",
    link: "https://www.youtube.com/watch?v=30nxF0nsQzo",
    rotation: "rotate-z-[-3deg]",
    name: "Kevin Le",
    img: "/images/profile-7.webp",
    translation: "translate-y-[10%]",
  },
];

export { flavorlists, cards };
